<?php

namespace Database\Seeders;

use App\Models\Product;
use Illuminate\Database\Seeder;

class ProductSeeder extends Seeder
{
    public function run(): void
    {
        $products = [
            [
                //1
                'title' => 'Yüksək Görüntü Kamera',
                'description' => 'Bir səhifənin düzəninə baxarkən oxuyucu səhifənin oxunaqlı məzmunu ilə diqqətinin yayılacağı artıq uzun müddət məlum olmuş bir faktdır.',
                'image' => 'products/p1.png',
                'images' => [
                    'products/p1.png',
                    'products/p1.png',
                    'products/p1.png',
                    'products/p1.png',
                ],

                'price' => 89.00,
                'has_stock' => true,
                'stock_quantity' => 10,
                'category_ids' => [3],
                'brand_ids' => 1,
                'tag_ids' => [1],
            ],
            [
                 //2
                'title' => 'Full HD WiFi Kamera',
                'description' => 'Full HD WiFi Kamera yüksək keyfiyyətli video təmin edərək problemsiz simsiz bağlantı təqdim edir. Bu kamera, ev və ofis təhlükəsizliyi üçün ideal olan aydın və detallı nəzarət görüntüləri təqdim etmək üçün hazırlanmışdır. Kameranın inkişaf etmiş xüsusiyyətlərinə hərəkət aşkarlama, real vaxt xəbərdarlıqları və ağıllı ev sistemləri ilə asan inteqrasiya daxildir.',
                'image' => 'products/p2.png',
                'images' => [
                    'products/p2.png',
                    'products/p2.png',
                    'products/p2.png',
                    'products/p2.png',
                ],

                'price' => 100,
                'has_stock' => true,
                'stock_quantity' => 5,
                'category_ids' => [3],
                'brand_ids' => 2,
                'tag_ids' => [1],
            ],
            [
                 //3
                'title' => 'Ağıllı Qapı Kilidi',
                'description' => 'Ağıllı Qapı Kilidi, asan quraşdırma və smartfon idarəetməsi ilə inkişaf etmiş təhlükəsizlik xüsusiyyətləri təklif edir. Bu innovativ kilid, açarsız giriş və real vaxtda daxilolma idarəçiliyi təmin edərək evinizin təhlükəsizliyini artırır.',
                'image' => 'products/p3.png',
                'images' => [
                    'products/p3.png',
                    'products/p3.png',
                    'products/p3.png',
                    'products/p3.png',
                ],

                'price' => 70,
                'has_stock' => true,
                'stock_quantity' => 5,
                'category_ids' => [3],
                'brand_ids' => 4,
                'tag_ids' => [3],
            ],
            [
                 //4
                'title' => 'Ultra HDR Kamera',
                'description' => 'Ultra HDR Kamera, ətraflı nəzarət üçün heyrətamiz yüksək dinamik aralıq video təqdim edir. Bu kamera, həm parlaq, həm də qaranlıq sahələrdə ən incə detalları çəkmək üçün hazırlanmışdır, bu da istənilən ərazi üçün yüksək keyfiyyətli video təmin edir. Xüsusiyyətləri arasında hərəkət aşkarlama, real vaxt xəbərdarlıqları və ağıllı ev sistemləri ilə problemsiz inteqrasiya daxildir. Güclü quruluşu və etibarlı performansı, hər hansı bir təhlükəsizlik quruluşu üçün onu ən yaxşı seçim edir.',
                'image' => 'products/p4.png',
                'images' => [
                    'products/p4.png',
                    'products/p4.png',
                    'products/p4.png',
                    'products/p4.png',
                ],

                'price' => 120,
                'has_stock' => true,
                'stock_quantity' => 5,
                'category_ids' => [3],
                'brand_ids' => 2,
                'tag_ids' => [1],
            ],
            [
                
                'title' => 'Simsiz Kamera',
                'description' => 'Simsiz Kamera, problemsiz bağlantı və yüksək keyfiyyətli video yazma təqdim edir. Bu kamera, hər yerdə rahatlıqla yerləşdirilə bilən çox yönlü və portativ bir təhlükəsizlik həlli axtaranlar üçün mükəmməldir. Simsiz xüsusiyyətləri sayəsində kabel idarə etməsi haqqında narahat olmadan asanlıqla istənilən yerdə yerləşdirilə bilər. Aydın video keyfiyyəti, hərəkət aşkarlama və real vaxtda bildirişlər təqdim edir. Kamera həmçinin müxtəlif ağıllı ev sistemləri ilə uyğun gəlir, bu da onu təhlükəsizlik quruluşunuza rahat bir əlavə edir.',
                'image' => 'products/p5.png',
                'images' => [
                    'products/p5.png',
                    'products/p5.png',
                    'products/p5.png',
                    'products/p5.png',
                ],

                'price' => 89,
                'has_stock' => true,
                'stock_quantity' => 5,
                'category_ids' => [3],
                'brand_ids' => 1,
                'tag_ids' => [2],
            ],
            [
                //6
                'title' => 'Vision Pro Kamera',
                'description' => 'Samsung-un Vision Pro Kamerası mükəmməl video keyfiyyəti və inkişaf etmiş xüsusiyyətlər təqdim edir, bu da onu peşəkar müşahidə və izləmə üçün əla seçim edir. Bu kamera möhtəşəm yüksək çözünürlüklü video təmin edir və artırılmış zoom qabiliyyətləri, ağıllı hərəkət aşkarlaması və mükəmməl gecə görmə kimi inkişaf etmiş funksionallıqlara malikdir. Onun davamlı dizaynı müxtəlif mühitlərdə etibarlılığını təmin edir, eyni zamanda ağıllı ev sistemləri ilə uyumluluğu onu rahat inteqrasiya etməyə imkan verir. Hem daxili, hem də xarici istifadəyə ideal olan Vision Pro Kamera, yüksək performans axtaranlar üçün mükəmməl bir həlldir.',
                'image' => 'products/p6.png',
                'images' => [
                    'products/p6.png',
                    'products/p6.png',
                    'products/p6.png',
                    'products/p6.png',
                ],
                'price' => 140,
                'has_stock' => true,
                'stock_quantity' => 5,
                'category_ids' => [3],
                'brand_ids' => 6,
                'tag_ids' => [1, 2],
            ],
            [
                //7
                'title' => 'Geniş Bucaqlı Ağıllı Kamera',
                'description' => 'Geniş Bucaqlı Ağıllı Kamera geniş bir baxış sahəsi təqdim edir, bu da onu geniş müşahidə və izləmə üçün ideal edir. Bu ağıllı kamera müxtəlif ağıllı ev sistemləri ilə problemsiz inteqrasiya olunur və uzaqdan idarəetmə, real vaxt bildirişləri və ağıllı hərəkət aşkarlaması kimi rahat xüsusiyyətlər təqdim edir. Şık dizaynı və yüksək çözünürlüklü video çəkilişi ilə, hətta zəif işıq şəraitində belə aydın və detallı görüntülər təmin edir. Kameranın simsiz funksionallığı ona çevik yerləşdirmə və asan quraşdırma imkanı verir, hər hansı bir ev və ya biznes üçün çox yönlü təhlükəsizlik həlli təqdim edir.',
                'image' => 'products/p7.png',
                'images' => [
                    'products/p7.png',
                    'products/p7.png',
                    'products/p7.png',
                    'products/p7.png',
                ],
                'price' => 90,
                'has_stock' => true,
                'stock_quantity' => 5,
                'category_ids' => [3],
                'brand_ids' => 1,
                'tag_ids' => [1, 2],
            ],
            [
                //8
                'title' => 'Dome Kamera',
                'description' => 'Dome Kamera müasir dizaynı və qabaqcıl texnologiyası ilə mükəmməl video keyfiyyəti və 360 dərəcə əhatə təmin edir. Geniş müşahidə üçün ideal olan bu kamera kompakt və qeyri-adi bir dome dizaynına malikdir, müxtəlif mühitlərdə problemsiz yerləşir. Yüksək çözünürlüklü video çəkmə və hərəkət aşkarlaması və gecə görmə kimi inkişaf etmiş xüsusiyyətlərə malikdir. Kameranın 360 dərəcə dönmə qabiliyyəti, məkanınızın tam əhatəsini təmin edir, bu da təhlükəsizliyi qorumaq və fəaliyyətləri izləmək üçün vacib bir alətdir. Asan quraşdırma və ağıllı ev sistemləri ilə inteqrasiya olmağı ilə Dome Kamera həm funksionallıq, həm də rahatlıq təqdim edir.',
                'image' => 'products/p8.png',
                'images' => [
                    'products/p8.png',
                    'products/p8.png',
                    'products/p8.png',
                    'products/p8.png',
                ],
                'price' => 89,
                'has_stock' => true,
                'stock_quantity' => 5,
                'category_ids' => [3],
                'brand_ids' => 4,
                'tag_ids' => [1, 3],
            ],
            [
                //9
                'title' => 'Simsiz Təhlükəsizlik Kamerası',
                'description' => 'HK Vision tərəfindən təqdim edilən Simsiz Təhlükəsizlik Kamerası simsiz bağlantı və yüksək çözünürlüklü çəkmə ilə etibarlı performans təmin edir. Bu kamera çevik yerləşdirmə və asan quraşdırma imkanı təqdim edir, həm yaşayış, həm də kommersiya təhlükəsizliyi ehtiyacları üçün əlverişli seçim edir. Aydın video keyfiyyəti təqdim edir və etibarlı simsiz ötürülmə ilə problemsiz izləmə təmin edir. Kamera qiymət və performans baxımından yüksək qiymətləndirilir, lakin zaman-zaman bağlantı problemləri müşahidə edilmişdir. Ümumiyyətlə, əsas təhlükəsizlik xüsusiyyətləri olan büdcəyə uyğun bir seçimdir.',
                'image' => 'products/p9.png',
                'images' => [
                    'products/p9.png',
                    'products/p9.png',
                    'products/p9.png',
                    'products/p9.png',
                ],
                'price' => 75,
                'has_stock' => true,
                'stock_quantity' => 5,
                'category_ids' => [3],
                'brand_ids' => 2,
                'tag_ids' => [1, 3],
            ],
            [
                //10
                'title' => 'Ağıllı Masa Kamerası',
                'description' => 'D-Link tərəfindən təqdim edilən Ağıllı Masa Kamerası yüksək çözünürlüklü video ehtiyacları üçün sərfəli bir həll təqdim edir, həm ev, həm də ofis mühitləri üçün idealdır. Bu kamera aydın və təmiz video keyfiyyəti təmin etmək üçün dizayn edilmişdir, həm gündəlik, həm də peşəkar istifadə üçün uygundur. Kompakt ölçüsü və asan quraşdırılması ilə Ağıllı Masa Kamerası hər hansı bir iş yerinə rahatlıqla yerləşir. Əsas təhlükəsizlik izləmə və video konfrans üçün etibarlı performans təklif edir, lakin daha yüksək video keyfiyyəti tələb edən istifadəçilər üçün uyğun olmaya bilər. Ümumiyyətlə, sadə və effektiv bir kamera həlli axtaranlar üçün sərfəli seçimdir.',
                'image' => 'products/p10.png',
                'images' => [
                    'products/p10.png',
                    'products/p10.png',
                    'products/p10.png',
                    'products/p10.png',
                ],
                'price' => 50,
                'has_stock' => true,
                'stock_quantity' => 5,
                'category_ids' => [3],
                'brand_ids' => 5,
                'tag_ids' => [3, 4],
            ],
            [
                //11
                "title" => "Yüksək Görüntü HD Kamera",
                "description" => "HK Vision-dən Yüksək Görüntü HD Kamera, yüksək dəqiqlikli video qeyd etmə qabiliyyəti ilə istisna video aydınlığı və detalları təmin edir. Yüksək performans üçün nəzərdə tutulmuş bu kamera, etibarlı və yüksək keyfiyyətli video müşahidə üçün inkişaf etmiş texnologiyalar təqdim edir. Quraşdırılması asan və istifadəçi dostu idarəetmə ilə həm yaşayış, həm də kommersiya təhlükəsizliyi tətbiqləri üçün uyğundur. Kameranın möhkəm dizaynı və etibarlı funksionallığı onu yüksək performanslı təhlükəsizlik həlli axtaranlar üçün əla seçim edir. Lakin istifadəçilər qeyd ediblər ki, video keyfiyyəti mükəmməl olsa da, əlaqəli tətbiq daha yaxşı inkişaf etdirilə bilər.",
                'image' => 'products/p11.png',
                'images' => [
                    'products/p11.png',
                    'products/p11.png',
                    'products/p11.png',
                    'products/p11.png',
                ],
                'price' => 130,
                'has_stock' => true,
                'stock_quantity' => 5,
                'category_ids' => [3],
                'brand_ids' => 2,
                'tag_ids' => [1, 5],
            ],
            [
                //12
                "title" => "Ağıllı HDR WiFi Kamera",
                "description" => "D-Link-dən Ağıllı HDR WiFi Kamera, yüksək dinamik diapazonlu video və problemsiz WiFi əlaqəsi ilə inkişaf etmiş xüsusiyyətlər və istifadəçi dostu performans təqdim edir. Bu kamera, artırılmış kontrast və rəng dəqiqliyi ilə canlı və detallı video qeyd etməyi təmin edir, bu da onu həm təhlükəsizlik, həm də gündəlik izləmə üçün ideal edir. İnkişaf etmiş WiFi imkanları asan əlaqə və uzaqdan nəzarət imkanı təmin edərək istifadəçilərə ərazilərini hər yerdən izləməyə imkan verir. Kamera mükəmməl video keyfiyyəti təklif etsə də, bəzi istifadəçilər tətbiqin daha intuitiv olması üçün inkişaf etdirilməsi lazım olduğunu qeyd ediblər. Ümumilikdə, HDR dəstəyi ilə yüksək keyfiyyətli video tələb edənlər üçün etibarlı seçimdir.",
                'image' => 'products/p12.png',
                'images' => [
                    'products/p12.png',
                    'products/p12.png',
                    'products/p12.png',
                    'products/p12.png',
                ],
                'price' => 100,
                'has_stock' => true,
                'stock_quantity' => 5,
                'category_ids' => [3],
                'brand_ids' => 5,
                'tag_ids' => [1, 5],
            ],
            [
                //13
                "title" => "Ağıllı Kilid",
                "description" => "Mobil tətbiq vasitəsilə asan giriş və təhlükəsizlik təmin edən ağıllı kilid.",
                'image' => 'products/p13.jpg',
                'images' => [
                    'products/p13.jpg',
                    'products/p13.jpg',
                    'products/p13.jpg',
                    'products/p13.jpg',
                ],
                'price' => 250,
                'has_stock' => true,
                'stock_quantity' => 5,
                'category_ids' => [1],
                'brand_ids' => 1,
                'tag_ids' => [3],
            ],
            [
                //14
                "title" => "Ağıllı Kilit",
                "description" => "Bluetooth texnologiyası ilə açarsız giriş təmin edən portativ ağıllı kilit.",
                'image' => 'products/p14.jpg',
                'images' => [
                    'products/p14.jpg',
                    'products/p14.jpg',
                    'products/p14.jpg',
                    'products/p14.jpg',
                ],
                'price' => 120,
                'has_stock' => true,
                'stock_quantity' => 5,
                'category_ids' => [1],
                'brand_ids' => 1,
                'tag_ids' => [3, 5],
            ],
            [
                //15
                "title" => "CCTV Kamera",
                "description" => "Gecə görmə və hərəkət aşkarlama xüsusiyyətləri ilə yüksək dəqiqlikli CCTV kamera.",
                'image' => 'products/p15.jpeg',
                'images' => [
                    'products/p15.jpeg',
                    'products/p15.jpeg',
                    'products/p15.jpeg',
                    'products/p15.jpeg',
                ],
                'price' => 200,
                'has_stock' => true,
                'stock_quantity' => 5,
                'category_ids' => [1],
                'brand_ids' => 2,
                'tag_ids' => [1, 3],
            ],

            [
                //16
                "title" => "IP Kamera",
                "description" => "Ən müasir hərəkət aşkar etmə və gecə görmə funksiyalarına sahib yüksək keyfiyyətli IP kamera.",
                'image' => 'products/p16.jpg',
                'images' => [
                    'products/p16.jpg',
                    'products/p16.jpg',
                    'products/p16.jpg',
                    'products/p16.jpg',
                ],
                'price' => 180,
                'has_stock' => true,
                'stock_quantity' => 5,
                'category_ids' => [1],
                'brand_ids' => 2,
                'tag_ids' => [1, 3],
            ],
            [
                //17
                "title" => "Ağıllı Zəng Qapısı",
                "description" => "İki tərəfli audio və HD video axınına sahib video zəng qapısı.",
                'image' => 'products/p17.jpg',
                'images' => [
                    'products/p17.jpg',
                    'products/p17.jpg',
                    'products/p17.jpg',
                    'products/p17.jpg',
                ],
                'price' => 150,
                'has_stock' => true,
                'stock_quantity' => 5,
                'category_ids' => [1],
                'brand_ids' => 4,
                'tag_ids' => [3],
            ],
            [
                //18
                "title" => "Evdə Təhlükəsizlik Kit",
                "description" => "Sensorlar və kameralarla tam təhlükəsizlik sistemi.",
                'image' => 'products/p18.jpg',
                'images' => [
                    'products/p18.jpg',
                    'products/p18.jpg',
                    'products/p18.jpg',
                    'products/p18.jpg',
                ],
                'price' => 300,
                'has_stock' => true,
                'stock_quantity' => 5,
                'category_ids' => [1],
                'brand_ids' => 4,
                'tag_ids' => [3, 5],
            ],
            [
                //19
                "title" => "Wi-Fi Router",
                "description" => "Yüksək sürətli internet dəstəyi ilə iki zolaqlı Wi-Fi router.",
                'image' => 'products/p19.webp',
                'images' => [
                    'products/p19.webp',
                    'products/p19.webp',
                    'products/p19.webp',
                    'products/p19.webp',
                ],
                'price' => 70,
                'has_stock' => true,
                'stock_quantity' => 5,
                'category_ids' => [1],
                'brand_ids' => 5,
                'tag_ids' => [2],
            ],
            [
                //20
                "title" => "igloohome Su Sızması Aşkar Edici",
                "description" => "Evdə və ofislərdə istifadə üçün mobil tətbiq vasitəsilə ağıllı xəbərdarlıqlar verən su sızması aşkar edici.",
                'image' => 'products/p20.webp',
                'images' => [
                    'products/p20.webp',
                    'products/p20.webp',
                    'products/p20.webp',
                    'products/p20.webp',
                ],
                'price' => 59,
                'has_stock' => true,
                'stock_quantity' => 5,
                'category_ids' => [1],
                'brand_ids' => 1,
                'tag_ids' => [2, 5],
            ],

            [
                //21
                "title" => "HIK Vision Su Sızması Aşkar Edici",
                "description" => "Yüksək həssaslıq və simsiz bağlantı ilə etibarlı su sızması aşkar edici.",
                'image' => 'products/p21.jpg',
                'images' => [
                    'products/p21.jpg',
                    'products/p21.jpg',
                    'products/p21.jpg',
                    'products/p21.jpg',
                ],
                'price' => 69.99,
                'has_stock' => true,
                'stock_quantity' => 5,
                'category_ids' => [1],
                'brand_ids' => 2,
                'tag_ids' => [5],
            ],
            [
                //22
                "title" => "Ezvir Ağıllı Sızma Aşkar Edici",
                "description" => "Mobil tətbiq inteqrasiyası və real-vaxtda bildirişlər ilə ağıllı su sızması aşkar edici.",
                'image' => 'products/p22.png',
                'images' => [
                    'products/p22.png',
                    'products/p22.png',
                    'products/p22.png',
                    'products/p22.png',
                ],
                'price' => 49.99,
                'has_stock' => true,
                'stock_quantity' => 5,
                'category_ids' => [1],
                'brand_ids' => 4,
                'tag_ids' => [3, 4],
            ],
            [
                //23
                "title" => "D-Link Su Sızması Sensoru",
                "description" => "Simsiz bağlantıya sahib su sızması sensoru və fərdiləşdirilə bilən xəbərdarlıq ayarları.",
                'image' => 'products/p23.jpg',
                'images' => [
                    'products/p23.jpg',
                    'products/p23.jpg',
                    'products/p23.jpg',
                    'products/p23.jpg',
                ],
                'price' => 39,
                'has_stock' => true,
                'stock_quantity' => 5,
                'category_ids' => [1],
                'brand_ids' => 5,
                'tag_ids' => [4],
            ],
            [
                //24
                "title" => "Samsung Ağıllı Sızma Aşkar Edici",
                "description" => "Mobil tətbiq inteqrasiyası və təcili bildirişlər ilə inkişaf etmiş ağıllı su sızması aşkar edici.",
                'image' => 'products/p24.jpeg',
                'images' => [
                    'products/p24.jpeg',
                    'products/p24.jpeg',
                    'products/p24.jpeg',
                    'products/p24.jpeg',
                ],
                'price' => 89,
                'has_stock' => true,
                'stock_quantity' => 5,
                'category_ids' => [1],
                'brand_ids' => 6,
                'tag_ids' => [4],
            ],
            [
                //25
                "title" => "CP Plus Təhlükəsizlik Kamera Sistemi",
                "description" => "Gecə görmə və hərəkət aşkar etmə xüsusiyyətlərinə sahib yüksək keyfiyyətli təhlükəsizlik kamera sistemi.",
                'image' => 'products/p25.jpg',
                'images' => [
                    'products/p25.jpg',
                    'products/p25.jpg',
                    'products/p25.jpg',
                    'products/p25.jpg',
                ],
                'price' => 199,
                'has_stock' => true,
                'stock_quantity' => 5,
                'category_ids' => [1],
                'brand_ids' => 7,
                'tag_ids' => [1, 3],
            ],
            [
                //26
                "title" => "igloohome Ağıllı Su Sızması Aşkar Edici",
                "description" => "Real-vaxtda bildirişlər və mobil tətbiq inteqrasiyası ilə ağıllı su sızması aşkar edici.",
                'image' => 'products/p26.webp',
                'images' => [
                    'products/p26.webp',
                    'products/p26.webp',
                    'products/p26.webp',
                    'products/p26.webp',
                ],
                'price' => 56,
                'has_stock' => true,
                'stock_quantity' => 5,
                'category_ids' => [1],
                'brand_ids' => 1,
                'tag_ids' => [3, 4],
            ],
            [
                //27
                "title" => "D-Link DCS-8600LH Xarici Kamera",
                "description" => "D-Link DCS-8600LH xarici kamera, tam HD 1080p həlli, gecə görmə və hava şəraitinə davamlı dizayna malikdir. Hərəkət aşkar etmə və bulud yaddaş opsiyaları da mövcuddur.",
                'image' => 'products/p27.jpg',
                'images' => [
                    'products/p27.jpg',
                    'products/p27.jpg',
                    'products/p27.jpg',
                    'products/p27.jpg',
                ],
                'price' => 139,
                'has_stock' => true,
                'stock_quantity' => 5,
                'category_ids' => [3, 4],
                'brand_ids' => 1,
                'tag_ids' => [3, 4],
            ],
            [
                // 28
                "title" => "Ağıllı Qapı Kilidi",
                "description" => "Igloohome Ağıllı Qapı Kilidi, evinizin təhlükəsizlik səviyyəsini maksimuma çatdırmaq üçün innovativ xüsusiyyətlər təqdim edir. Bu kilid, uzaqdan idarəetmə funksiyası ilə evinizə giriş imkanlarını asanlaşdırır və çoxsaylı təhlükəsizlik protokollarını dəstəkləyir. Müasir dizaynı ilə həm estetik görünüşə, həm də funksionallığa malikdir.",
                'image' => 'products/p28.jpg',
                'images' => [
                    'products/p28.jpg',
                    'products/p28.jpg',
                    'products/p28.jpg',
                    'products/p28.jpg',
                ],
                'price' => 299,
                'has_stock' => true,
                'stock_quantity' => 5,
                'category_ids' => [4],
                'brand_ids' => 1,
                'tag_ids' => [3],
            ],
            [
                // 29
                "title" => "Açıq Hava Təhlükəsizlik Kamerası",
                "description" => "HIK Vision Açıq Hava Təhlükəsizlik Kamerası, hər cür hava şəraitinə davamlı materiallardan hazırlanıb. Bu kamera, gecə və gündüz yüksək keyfiyyətli görüntü təqdim edərək ətraf mühitinizi təhlükəsiz saxlamaq üçün əla vasitədir. Həmçinin, uzaqdan izləmə funksiyası ilə təhlükəsizliyinizi hər an nəzarətdə saxlayın.",
                'image' => 'products/p29.webp',
                'images' => [
                    'products/p29.webp',
                    'products/p29.webp',
                    'products/p29.webp',
                    'products/p29.webp',
                ],
                'price' => 179,
                'has_stock' => true,
                'stock_quantity' => 5,
                'category_ids' => [4],
                'brand_ids' => 2,
                'tag_ids' => [1, 3],
            ],
            [
                // 30
                "title" => "WiFi Qapı Zəngi Kamerası",
                "description" => "Ezvir WiFi Qapı Zəngi Kamerası, həm təhlükəsizlik, həm də müasir texnologiya ilə rahatlığı birləşdirir. Bu cihaz, yüksək dəqiqlikli video çəkiliş və ağıllı bildiriş funksiyaları ilə evinizin təhlükəsizlik səviyyəsini artırır. Rahat quraşdırma və istifadəyə uyğun dizayn xüsusiyyətləri ilə hər kəsin diqqətini cəlb edir.",
                'image' => 'products/p30.webp',
                'images' => [
                    'products/p30.webp',
                    'products/p30.webp',
                    'products/p30.webp',
                    'products/p30.webp',
                ],
                'price' => 99,
                'has_stock' => true,
                'stock_quantity' => 5,
                'category_ids' => [4],
                'brand_ids' => 2,
                'tag_ids' => [1, 3],
            ],
            [
                // 31
                "title" => "Ağıllı Hərəkət Sensoru",
                "description" => "D-Link Ağıllı Hərəkət Sensoru, yüksək həssaslıqda hərəkət aşkarlama xüsusiyyəti ilə evinizdə tam təhlükəsizlik yaradır. Bu sensor, hərəkəti anında qeyd edir və bildiriş göndərir. Evinizin hər küncünü əhatə edən bu cihaz, modern texnologiyanın ən yaxşı nümunələrindən biridir.",
                'image' => 'products/p31.jpg',
                'images' => [
                    'products/p31.jpg',
                    'products/p31.jpg',
                    'products/p31.jpg',
                    'products/p31.jpg',
                ],
                'price' => 89,
                'has_stock' => true,
                'stock_quantity' => 5,
                'category_ids' => [4],
                'brand_ids' => 5,
                'tag_ids' => [1, 3],
            ],
            [
                // 32
                "title" => "Ağıllı İşıq Lampası",
                "description" => "Samsung Ağıllı İşıq Lampası, müxtəlif rəng rejimləri və enerji qənaət rejimi ilə evinizi bəzəyən mükəmməl seçimdir. Müasir görünüşü ilə həm dekorativ, həm də funksional tələbləri qarşılayan bu lampa, ağıllı ev texnologiyasının ideal nümunəsidir. İşıqlandırmada yenilik axtaranlar üçün mükəmməl həll yoludur.",
                'image' => 'products/p32.jpeg',
                'images' => [
                    'products/p32.jpeg',
                    'products/p32.jpeg',
                    'products/p32.jpeg',
                    'products/p32.jpeg',
                ],
                'price' => 60,
                'has_stock' => true,
                'stock_quantity' => 5,
                'category_ids' => [4],
                'brand_ids' => 6,
                'tag_ids' => [3],
            ],
            [
                //33
                "title" => "Simsiz Təhlükəsizlik Kamerası",
                "description" => "CP Plus simsiz təhlükəsizlik kamerası, yüksək dəqiqlikli görüntü imkanları ilə evinizi və ya iş yerinizi qorumağa kömək edir. Gecə görmə funksiyası və uzaqdan idarəetmə imkanı ilə təhlükəsizliyi daha da artırır. Bu cihaz, həmçinin sadə quraşdırma və etibarlı istifadə təmin edir.",
                'image' => 'products/p33.jpeg',
                'images' => [
                    'products/p33.jpeg',
                    'products/p33.jpeg',
                    'products/p33.jpeg',
                    'products/p33.jpeg',
                ],
                'price' => 129,
                'has_stock' => true,
                'stock_quantity' => 5,
                'category_ids' => [4],
                'brand_ids' => 7,
                'tag_ids' => [1],
            ],
            [
                //34
                "title" => "Ağıllı Barmaq İzi Qapı Kilidi",
                "description" => "Igloohome ağıllı barmaq izi qapı kilidi, biometrik təhlükəsizlik texnologiyası ilə evinizə maksimum müdafiə təmin edir. Estetik dizaynı ilə hər növ interyerə uyğunlaşır və istifadə rahatlığı təqdim edir. Elektron idarəetmə funksiyaları ilə təchiz edilmişdir.",
                'image' => 'products/p34.webp',
                'images' => [
                    'products/p34.webp',
                    'products/p34.webp',
                    'products/p34.webp',
                    'products/p34.webp',
                ],
                'price' => 349,
                'has_stock' => true,
                'stock_quantity' => 5,
                'category_ids' => [4],
                'brand_ids' => 1,
                'tag_ids' => [3],
            ],
            [
                //35
                "title" => "Daxili Ağıllı Kamera",
                "description" => "HIK Vision daxili ağıllı kamera, yüksək keyfiyyətli video izləmə texnologiyası ilə evinizin daxili təhlükəsizliyini təmin edir. Kompakt ölçüləri və sadə quraşdırma prosesinə malikdir. Həmçinin, mobil cihazlarla inteqrasiya edilərək uzaqdan idarə olunma imkanı yaradır.",
                'image' => 'products/p35.jpeg',
                'images' => [
                    'products/p35.jpeg',
                    'products/p35.jpeg',
                    'products/p35.jpeg',
                    'products/p35.jpeg',
                ],
                'price' => 159,
                'has_stock' => true,
                'stock_quantity' => 5,
                'category_ids' => [4],
                'brand_ids' => 2,
                'tag_ids' => [1, 3],
            ],
            [
                //36
                "title" => "Samsung SmartThings Hub",
                "description" => "Samsung SmartThings Hub, müxtəlif ağıllı ev cihazlarını birləşdirir və idarə edir. Bu cihaz, müxtəlif cihazların avtomatlaşdırılmasını və inteqrasiyasını asanlaşdırır. Geniş ağıllı ev ekosistemləri ilə uyğun işləməyi təmin edir.",
                'image' => 'products/p36.jpg',
                'images' => [
                    'products/p36.jpg',
                    'products/p36.jpg',
                    'products/p36.jpg',
                    'products/p36.jpg',
                ],
                'price' => 99,
                'has_stock' => true,
                'stock_quantity' => 5,
                'category_ids' => [4],
                'brand_ids' => 6,
                'tag_ids' => [3],
            ],
            [
                //37
                "title" => "Igloohome Ağıllı Tüstü Alarmı",
                "description" => "Wi-Fi ilə idarə olunan Igloohome ağıllı tüstü alarmı, yanğın təhlükəsini vaxtında aşkar edərək sizi xəbərdar edir. Şık dizaynı və yüksək funksionallığı ilə həm evlər, həm də iş yerləri üçün ideal seçimdir.",
                'image' => 'products/p37.webp',
                'images' => [
                    'products/p37.webp',
                    'products/p37.webp',
                    'products/p37.webp',
                    'products/p37.webp',
                ],
                'price' => 120,
                'has_stock' => true,
                'stock_quantity' => 5,
                'category_ids' => [5],
                'brand_ids' => 1,
                'tag_ids' => [3],
            ],
            [
                //38
                "title" => "Smoke Detector Pro",
                "description" => "HIK Vision texnologiyası ilə hazırlanmış yüksək həssasiyyətli smoke detector. Bu cihaz, ən kiçik təhlükələri belə aşkar edərək maksimum təhlükəsizlik təmin edir. Kompakt dizaynı ilə istifadəsi asandır.",
                'image' => 'products/p38.jpg',
                'images' => [
                    'products/p38.jpg',
                    'products/p38.jpg',
                    'products/p38.jpg',
                    'products/p38.jpg',
                ],
                'price' => 140,
                'has_stock' => true,
                'stock_quantity' => 5,
                'category_ids' => [5],
                'brand_ids' => 2,
                'tag_ids' => [3],
            ],
            [
                //39
                "title" => "Təhlükəsizlik Sistemi Təkmilləşdirilmiş Tüstü Alarmı",
                "description" => "Bu yüksək performanslı tüstü alarmı ev və ofislər üçün ideal seçimdir. Təmiz dizayn və yüksək dəqiqliklə hazırlanmış cihaz təhlükəsizlik tədbirlərinizi maksimuma çatdırır. Həmçinin, uzunömürlülük və davamlılıqla yanaşı, istifadə rahatlığı ilə seçilir.",
                'image' => 'products/p39.jpg',
                'images' => [
                    'products/p39.jpg',
                    'products/p39.jpg',
                    'products/p39.jpg',
                    'products/p39.jpg',
                ],
                'price' => 100,
                'has_stock' => true,
                'stock_quantity' => 5,
                'category_ids' => [5],
                'brand_ids' => 4,
                'tag_ids' => [3],
            ],
            [
                //40
                "title" => "Ezviz Smart Tüstü Detektoru",
                "description" => "Ezviz-in ən son texnologiyasına sahib bu tüstü detektoru müasir həyat tərzinizə uyğunlaşdırılmışdır. Cihaz, minimal dizaynı və yüksək həssas sensorları ilə həm gözəllik, həm də funksionallığı bir araya gətirir. Kiçik ölçülərinə baxmayaraq, böyük təhlükəsizlik tədbirləri üçün nəzərdə tutulmuşdur.",
                'image' => 'products/p40.jpeg',
                'images' => [
                    'products/p40.jpeg',
                    'products/p40.jpeg',
                    'products/p40.jpeg',
                    'products/p40.jpeg',
                ],
                'price' => 110,
                'has_stock' => true,
                'stock_quantity' => 5,
                'category_ids' => [5],
                'brand_ids' => 4,
                'tag_ids' => [3],
            ],
            [
                //41
                "title" => "Simsiz Tüstü Alarmı",
                "description" => "Bu simsiz tüstü alarmı Ezviz-in müasir texnologiyaları ilə təchiz edilmişdir. Kabelsiz işləmə rahatlığı ilə yanaşı, yüksək həssas sensorları hər cür tüstü və təhlükəni dəqiq şəkildə aşkarlayır. Minimal dizayn və portativliyi ilə bu cihaz təhlükəsizlik tədbirlərinizi artırmaq üçün əvəzolunmazdır.",
                'image' => 'products/p41.webp',
                'images' => [
                    'products/p41.webp',
                    'products/p41.webp',
                    'products/p41.webp',
                    'products/p41.webp',
                ],
                'price' => 95,
                'has_stock' => true,
                'stock_quantity' => 5,
                'category_ids' => [5],
                'brand_ids' => 5,
                'tag_ids' => [3],
            ],
            [
                //42
                "title" => "Tüstü Alarm Plus",
                "description" => "Samsung markasının yüksək keyfiyyəti ilə təqdim olunan bu tüstü alarmı təhlükəsizlik üçün müasir həllər təklif edir. Cihaz, yüksək performans və uzunömürlü materiallarla istehsal olunmuşdur. Ev və ya iş yerlərində istifadə üçün ideal seçimdir.",
                'image' => 'products/p42.jpg',
                'images' => [
                    'products/p42.jpg',
                    'products/p42.jpg',
                    'products/p42.jpg',
                    'products/p42.jpg',
                ],
                'price' => 130,
                'has_stock' => true,
                'stock_quantity' => 5,
                'category_ids' => [5],
                'brand_ids' => 6,
                'tag_ids' => [3],
            ],
            [
                //43
                "title" => "Ultra Tüstü Detektoru",
                "description" => "CP Plus texnologiyasına əsaslanan bu tüstü detektoru ən yüksək standartlara cavab verir. Yüksək həssas sensorları və davamlı dizaynı ilə bu cihaz təhlükəsizliyinizə maksimum dərəcədə xidmət edəcək. Hər bir detala diqqət yetirərək, bu detektor ən yüksək performansı təmin edir.",
                'image' => 'products/p43.png',
                'images' => [
                    'products/p43.png',
                    'products/p43.png',
                    'products/p43.png',
                    'products/p43.png',
                ],
                'price' => 150,
                'has_stock' => true,
                'stock_quantity' => 5,
                'category_ids' => [5],
                'brand_ids' => 7,
                'tag_ids' => [3],
            ],
            [
                //44
                "title" => "Mini Tüstü Alarmı",
                "description" => "Igloohome markasının kiçik ölçülü tüstü alarmı yüksək funksionallıq təklif edir. Kompakt dizaynı ilə bu cihaz rahatlıqla daşınır və istifadəsi çox sadədir. Hər növ tüstü və təhlükəni dərhal aşkar edərək təhlükəsizliyinizə təminat verir.",
                'image' => 'products/p44.jpg',
                'images' => [
                    'products/p44.jpg',
                    'products/p44.jpg',
                    'products/p44.jpg',
                    'products/p44.jpg',
                ],
                'price' => 80,
                'has_stock' => true,
                'stock_quantity' => 5,
                'category_ids' => [5],
                'brand_ids' => 1,
                'tag_ids' => [3],
            ],
            [
                //45
                "title" => "İkiqat Sensorlu Tüstü Alarmı",
                "description" => "İkiqat sensor texnologiyasına malik olan bu tüstü alarmı ən kiçik detallarını belə müəyyən edir. Geniş təhlükəsizlik tədbirləri üçün nəzərdə tutulmuş cihaz müasir dizayn və yüksək həssaslığı birləşdirir. Ev və ofislərdə təhlükəsizliyinizi təmin etmək üçün ideal seçimdir.",
                'image' => 'products/p45.png',
                'images' => [
                    'products/p45.png',
                    'products/p45.png',
                    'products/p45.png',
                    'products/p45.png',
                ],
                'price' => 150,
                'has_stock' => true,
                'stock_quantity' => 5,
                'category_ids' => [5],
                'brand_ids' => 2,
                'tag_ids' => [3],
            ],

            [
                "title" => "Igloohome Smart Leakage Detector",
                "description" => "Igloohome tərəfindən təqdim olunan bu ağıllı sızma detektoru müasir texnologiya ilə təchiz olunmuşdur. Cihaz su sızmalarını tez bir zamanda aşkarlayaraq evinizi təhlükəsiz saxlayır.",
                'image' => 'products/p46.webp',
                'images' => [
                    'products/p46.webp',
                    'products/p46.webp',
                    'products/p46.webp',
                    'products/p46.webp',
                ],
                "price" => 120,
                "has_stock" => true,
                "stock_quantity" => 5,
                "category_ids" => [2], // Leakage Detector
                "brand_ids" => 1, // Igloohome
                "tag_ids" => [4], // Su ilə bağlı təhlükəsizlik
            ],
            [
                "title" => "HIK Vision Advanced Water Leakage Sensor",
                "description" => "HIK Vision markasından yüksək dəqiqlikli su sızma detektoru. Təhlükəsizlik sisteminizə mükəmməl əlavə olan bu cihazla hər bir sızmanı anında aşkar edin.",
                'image' => 'products/p47.webp',
                'images' => [
                    'products/p47.webp',
                    'products/p47.webp',
                    'products/p47.webp',
                    'products/p47.webp',
                ],
                "price" => 150,
                "has_stock" => true,
                "stock_quantity" => 5,
                "category_ids" => [2],
                "brand_ids" => 2,
                "tag_ids" => [4],
            ],
            [
                "title" => "D-Link Smart Water Sensor",
                "description" => "D-Link tərəfindən təqdim olunan bu ağıllı su sensoru sızmaları dəqiq və tez bir zamanda aşkarlayır. Cihaz, təhlükəsizlik tədbirləriniz üçün vacib bir hissədir.",
                'image' => 'products/p48.webp',
                'images' => [
                    'products/p48.webp',
                    'products/p48.webp',
                    'products/p48.webp',
                    'products/p48.webp',
                ],
                "price" => 125,
                "has_stock" => true,
                "stock_quantity" => 5,
                "category_ids" => [2],
                "brand_ids" => 5,
                "tag_ids" => [4],
            ],
            [
                "title" => "Samsung Premium Leakage Detector",
                "description" => "Samsung markasından yüksək keyfiyyətli və davamlı sızma detektoru. Ev və iş yerləri üçün ideal olan bu cihazla təhlükəsizlik tədbirlərinizi maksimuma çatdırın.",
                'image' => 'products/p49.webp',
                'images' => [
                    'products/p49.webp',
                    'products/p49.webp',
                    'products/p49.webp',
                    'products/p49.webp',
                ],
                "price" => 200,
                "has_stock" => true,
                "stock_quantity" => 5,
                "category_ids" => [2],
                "brand_ids" => 6,
                "tag_ids" => [4],
            ],
            [
                "title" => "CP Plus Ultra Water Leakage Alarm",
                "description" => "CP Plus texnologiyasına əsaslanan bu cihaz su sızmalarını etibarlı şəkildə aşkarlayır. Kompakt dizaynı və asan istifadəsi ilə seçilir.",
                'image' => 'products/p50.jpeg',
                'images' => [
                    'products/p50.jpeg',
                    'products/p50.jpeg',
                    'products/p50.jpeg',
                    'products/p50.jpeg',
                ],
                "price" => 180,
                "has_stock" => true,
                "stock_quantity" => 5,
                "category_ids" => [2],
                "brand_ids" => 7,
                "tag_ids" => [4],
            ],
            [
                "title" => "Igloohome Compact Leakage Detector",
                "description" => "Kiçik ölçülü, lakin yüksək funksionallıqlı Igloohome sızma detektoru su sızmalarını dərhal aşkarlayır və təhlükəsizliyinizə xidmət edir.",
                'image' => 'products/p51.jpg',
                'images' => [
                    'products/p51.jpg',
                    'products/p51.jpg',
                    'products/p51.jpg',
                    'products/p51.jpg',
                ],
                "price" => 110,
                "has_stock" => true,
                "stock_quantity" => 5,
                "category_ids" => [2],
                "brand_ids" => 1,
                "tag_ids" => [4],
            ],
            [
                "title" => "HIK Vision Mini Water Sensor",
                "description" => "HIK Vision tərəfindən hazırlanmış kiçik ölçülü su sensoru ev və ofis təhlükəsizliyiniz üçün nəzərdə tutulmuşdur. Quraşdırılması asandır və effektiv nəticələr təmin edir.",
                'image' => 'products/p52.jpg',
                'images' => [
                    'products/p52.jpg',
                    'products/p52.jpg',
                    'products/p52.jpg',
                    'products/p52.jpg',
                ],
                "price" => 105,
                "has_stock" => true,
                "stock_quantity" => 5,
                "category_ids" => [2],
                "brand_ids" => 2,
                "tag_ids" => [4],
            ],
            [
                "title" => "CP Plus High-Tech Leakage Detector",
                "description" => "CP Plus texnologiyası ilə hazırlanmış bu cihaz müasir təhlükəsizlik həlləri üçün ideal seçimdir. Su sızmalarını yüksək dəqiqliklə aşkarlayır.",
                'image' => 'products/p53.webp',
                'images' => [
                    'products/p53.webp',
                    'products/p53.webp',
                    'products/p53.webp',
                    'products/p53.webp',
                ],
                "price" => 170,
                "has_stock" => true,
                "stock_quantity" => 5,
                "category_ids" => [2],
                "brand_ids" => 7,
                "tag_ids" => [4],
            ],
            [
                "title" => "Igloohome Ağıllı Sızma Sensoru",
                "description" => "Igloohome-un yeni nəsil ağıllı su sensoru ev və iş yerlərində istifadə üçün nəzərdə tutulmuşdur. Kompakt dizayn və yüksək funksionallıqla təhlükəsizliyinizə xidmət edir.",
                'image' => 'products/p54.jpg',
                'images' => [
                    'products/p54.jpg',
                    'products/p54.jpg',
                    'products/p54.jpg',
                    'products/p54.jpg',
                ],
                "price" => 115,
                "has_stock" => true,
                "stock_quantity" => 5,
                "category_ids" => [2],
                "brand_ids" => 1,
                "tag_ids" => [4],
            ],


        ];



        foreach ($products as $productData) {
            $product = Product::create([
                'title' => $productData['title'],
                'description' => $productData['description'],
                'image' => $productData['image'],
                'images' => $productData['images'],
                'price' => $productData['price'],
                'has_stock' => $productData['has_stock'],
                'stock_quantity' => $productData['stock_quantity'],
            ]);

            $product->categories()->attach($productData['category_ids']);
            $product->brands()->attach($productData['brand_ids']);
            $product->tags()->attach($productData['tag_ids']);
        }
    }
}
